# Generated by Django 3.2.4 on 2021-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_total_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='total',
            field=models.FloatField(),
        ),
    ]
